Tests have been restored. Two of them are failing (should be passing).
The first test is looking for a system library (libselinux.so.1)
which is not (by default) present on Arch Linux.

The second one is failing because it compares the output string
of the --version parameter of a program:

AssertionError: 'eHogKFhaIFV0aWxzKSA1LjEuMGFscGhhCmxpYmx6bWEgNS4yLjMK' !=
    u'eHogKFhaIFV0aWxzKSA1LjEuMGFscGhhCmxpYmx6bWEgNS4xLjBhbHBoYQo='

echo 'eHogKFhaIFV0aWxzKSA1LjEuMGFscGhhCmxpYmx6bWEgNS4xLjBhbHBoYQo=' | base64 -d
xz (XZ Utils) 5.1.0alpha
liblzma 5.1.0alpha

echo 'eHogKFhaIFV0aWxzKSA1LjEuMGFscGhhCmxpYmx6bWEgNS4yLjMK' | base64 -d
xz (XZ Utils) 5.1.0alpha
liblzma 5.2.3